# Module manifest for module "PSFileMirror"
# Generated by: Phil Carney
# Generated on: 05/12/2018
@{
    ModuleVersion     = "0.1.6"
    RootModule        = "PSFileMirror.psm1"
    GUID              = "60bd8597-e3ef-4c9c-9467-55bfa5a3ee80"
    Author            = "Phil Carney"
    CompanyName       = "N/A"
    Copyright         = "Phil Carney - 2018"
    Description       = "A simple Powershell-only (6+) file mirroring solution"
    PowerShellVersion = "6.0"
    FunctionsToExport = @("Invoke-FileMirror")
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    PrivateData       = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()
            LicenseUri   = "https://github.com/philccarney/PSFileMirror/blob/master/licence.md"
            ProjectUri   = "https://github.com/philccarney/PSFileMirror"
            ReleaseNotes = "https://github.com/philccarney/PSFileMirror/releases"
        }
    }
}