#
# Module manifest for module 'PSFileMirror'
# Generated by: Phil Carney
# Generated on: 05/12/2018

@{
    ModuleVersion     = '0.1.6'
    RootModule        = "PSFileMirror.psm1"
    GUID              = '60bd8597-e3ef-4c9c-9467-55bfa5a3ee80'
    Author            = 'Phil Carney'
    CompanyName       = 'N/A'
    Copyright         = 'Phil Carney - 2018'
    Description       = 'A Powershell Core-based module solution for copying/mirroring files and folders between locations.'
    PowerShellVersion = '6.0'
    FunctionsToExport = @("Invoke-FileMirror")
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()
            # A URL to the license for this module.
            # LicenseUri = ''
            # A URL to the main website for this project.
            # ProjectUri = ''
            # A URL to an icon representing this module.
            # IconUri = ''
            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

}